### ISSUE TITLE
Possibility of Creating an App for Sharing Small Bits of Data Via Ultrasound

### ISSUE THREAD

**Issue by moriel5** [kaputnikGo/PilferShush_prod#2]
Hi, this looks great, especially without requiring Google's Play Services.
What do you think about the idea of creating an app that is meant to share small bits of data, such as links or contacts, via ultrasound.

Radon does this, however it relies on Google's Nearby API, which obviously is not an option for noGAPPS hsers.

**Comment by kaputnikGo** [comment]
There are many around, most of which are attached to privacy invasion companies or at the least advertising/trackers.
This group, however, may provide good use of NUHF via open source etc :
 https://sonitalk.fhstp.ac.at/

**Comment by moriel5** [comment]
That sounds great!
Thanks for the information.
